install("optparse")
install("BiocManager")
install("remotes")
install("bioc::scDblFinder")
install("Liuy12/seurat-object")
install("Liuy12/seurat")
install("bnprks/BPCells/r")
install("immunogenomics/presto")
install("bioc::glmGamPoi")
install("R.utils")
install('satijalab/seurat-wrappers')
install('bioc::Banksy')

install('SoupX')

install("pwwang/scplotter")
install('ggplot2', prompt = FALSE)
install("patchwork", prompt = FALSE)
install("hdf5r", prompt = FALSE)
install("openxlsx", prompt = FALSE)
install("dplyr", prompt = FALSE)
install("reshape2", prompt = FALSE)
install("gridExtra", prompt = FALSE)
install("RColorBrewer", prompt = FALSE)
install("rmarkdown", prompt = FALSE)
install("rmdformats", prompt = FALSE)
install("future", prompt = FALSE)
install("doFuture", prompt = FALSE)
install("harmony", prompt = FALSE)
install("DT", prompt = FALSE)



requiredPacks <- c('optparse','scDblFinder','SoupX','ggplot2','patchwork','BPCells','presto','glmGamPoi','SeuratWrappers','Banksy','dplyr','openxlsx','rmdformats','rmarkdown','reshape2','gridExtra','ggplot2','future','doFuture','Seurat','SeuratObject','RColorBrewer','harmony','DT', 'hdf5r', 'grid')
for(i in requiredPacks){
  if(!require(i, character.only = T)) {print(paste0('package ',i,' is not available. Please check the version of R and R library path'))}}

library("optparse")
library("scDblFinder")
library("SoupX")
library("ggplot2")
library("patchwork")
library("BPCells")
library("presto")
library("glmGamPoi")
library("SeuratWrappers")
library("Banksy")
library("dplyr")
library("openxlsx")
library("rmdformats")
library("rmarkdown")
library("reshape2")
library("gridExtra")
library("ggplot2")
library("future")
library("doFuture")
library("Seurat")
library("SeuratObject")
library("RColorBrewer")
library("harmony")
library("DT")
library("hdf5r")


